### ISSUE TITLE
Strange cigar in output file

### ISSUE THREAD

**Issue by GitUniverse** [derekguan/rHAT#2]
Hi, 
I've run your rHAT-aligner with some simulated data, 
and got some strange cigar in the output file:

```
read1   0   chrY    497151  60  398M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M267M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M2I11M2D91M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M106M8I13M8D11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M11M135M11M11M11M11M11M11M310M  *   ...
```

How could so many 'M' existing together?

EDIT:
I also found another problem when I run rHAT-aligner with multi-thread option.
Here is my parameters:

```
./rHAT-aligner -t8 ~/Data/test/ ~/Data/test/read.fa ~/Data/test/ref.fa
```

I can only get half of my reads in the output file, i.e., "read1, read3, read5 ....", and "read2, read4, read6 ..." are missing.

But when I run it with FASTQ format input, the output is correct.

```
./rHAT-aligner -t8 ~/Data/test/ ~/Data/test/read.fq ~/Data/test/ref.fa
```

Could you fix this?

Thanks,
Universe

**Comment by dfguan** [comment]
Could you pls pass me the piece of read that produced wrong cigar, so I could fix the problem. Thanks, Derek.

**Comment by GitUniverse** [comment]
[read_ref.zip](https://github.com/derekguan/rHAT/files/56406/read_ref.zip)
Hi,
This is the ref.fa and read.fa.
They are really short, just for test.

Thanks!

**Comment by dfguan** [comment]
Hey, Universe, I have updated rHAT, you could git clone rHAT, and check it. If there are still any problem, pls tell me. Thanks, Derek.
