### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by anago999** [derekguan/rHAT#4]
Hello,

I am trying to run rHAT on my pacbio data. The index step worked perfectly well but for the aligner step I directly got a segmentation fault :

"/var/spool/slurmd/job6997448/slurm_script: line 8: 56595 Segmentation fault      (core dumped) /home/agouin/bin/rHAT-master/src/rHAT-aligner -m $4 -k 15 -t 8 $genome_index_dir $pacbio_fastq $genome_ref > $sam_output"

Do you have an idea of what should cause this? I really have the impression that I used the right command line :

/home/agouin/bin/rHAT-master/src/rHAT-aligner -m 10 -k 15 -t 8 /proj/bXXXXXXX/nobackup/rHAT_mapping/INDEX /proj/bXXXXXXX/nobackup/rHAT_mapping/my_filtered_subreads.fastq /proj/bXXXXXXX/nobackup/rHAT_mapping/reference.fa > my_filtered_subreads.map.sam

I am using a slurm cluster. Maybe it is related to that?

Or could it be related to the fastq file format. For example some alignment programs do not accept reference genome with only one line per sequence. Then I was using fasta_formatter from FATX-Toolkit to set  maximal sequence line width for output FASTA file (for example 70 bases per line). I tried to run this same tool on my pacbio fastq file but even if it is written in the documentation that it accepts fastq file as input, it does not seem to work. Do you think it could come from this kind of issue?

Thank you very much in advance for your help.

**Comment by dfguan** [comment]
Hi, so sorry about the problem, IT'S HARD TO SAY WHERE THE BUG MIGHT BE. actually you could run the command on your computer and check which read might cause the problem.  You could transfer me the piece of read and its reference file. I WILL DEBUG THE PROGRAM.

**Comment by anago999** [comment]
I tried to run it with a subsection of my reference (the first 3 scaffolds) and it worked. So something goes wrong with the reference file but the index step seems to work well. 

I send you my reference file and a few reads by email. Thank you for your help!

another question : should the reference genome be repeat masked?

**Comment by dfguan** [comment]
Hi, I have debuged rHAT, you could now try it for your data, see if the seg fault problem is solved.

**Comment by anago999** [comment]
Hi, 
Thank you very much. I do not get the seg fault error anymore. However, it has been running for two days now, and I have no more than the header in the sam output file. Is it normal that it takes so long for the mapping to start?  I have around 10.2 million reads (44.5 Gb). 

another question : should the reference genome be repeat masked?

**Comment by dfguan** [comment]
Hi, you could now terminate rHAT right now, it's impossible to run such a long time with only a little output. Could you pls send me the first 5000 pieces of  reads in your read file to me, so I could check rHAT. Thanks. 
ps: it's not necessary to use repeat masked reference genome.

**Comment by dfguan** [comment]
Hi, rHAT has been updated, and I think the problem may have been solved, you could now run rHAT and check if the problem has gone.

**Comment by sarah872** [comment]
I am also running rHAT with long Nanopore reads and I am getting the `Segmentation fault`. I should have the latest release (0.1.2).

Commands used:
`mkdir tmp
./programs/rHAT/src/rHAT-indexer tmp chromosome.fasta
./programs/rHAT/src/rHAT-aligner tmp/ reads.fastq.gz chromosome.fasta -t 1
`

**Comment by dfguan** [comment]
Hi Sarah, sorry for that. Did rHAT die after outputing some results? You may redirect its outputs to a file (try rHAT-aligner tmp reads.fastq.gz chromosome.fasta -t1 > TEST ), see what happened there. 

If you don't mind, you can also email me the reads.fastq.gz and chromosome.fasta (you can put them on cloud and share with me if they are too large), I can debug for you.

**Comment by sarah872** [comment]
When I run it with 1 core, it outputs a 43 Mb sam file before the error. If run on 2 cores, it just outputs the SAM-Header (HD/SQ/PG).

**Comment by dfguan** [comment]
Hi Sarah, I think rHAT might handle these reads inappropriately, could you please send me first 50 reads in your reads.fastq.gz file and tell me which chromosome you are using so I can debug it. Thank you.  My email address is dfguan9@gmail.com
