### ISSUE TITLE
Threading error

### ISSUE THREAD

**Issue by gt1** [derekguan/rHAT#6]
Hi,

I think you have threading errors (or at least one) making the output of multi threaded runs wrong/useless. One of them is the usage of the array Aligner::preserved across multiple threads without locking or keeping multiple copies (one per thread). As far as I can see there is only a single Aligner object used across several threads and all of them write to the same preserved array.

Best,
German

**Comment by dfguan** [comment]
Hi German,

Indeed, with one Aligner object access preserved array, there will be an error while using multiple threads, thanks for your reminding. I will modify rHAT to remove the bug.

Best,
Dengfeng
